# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpx" do
  name "mcpx"
  desc "Unix-native CLI wrapper for MCP servers"
  homepage "https://github.com/lydakis/mcpx"
  version "0.1.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpx"

  on_macos do
    on_intel do
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_darwin_amd64.tar.gz"
      sha256 "d5e346ebc1aa1432b590224cb8bbc637447342393f7ab44e6f16e0b920fe701a"
    end
    on_arm do
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_darwin_arm64.tar.gz"
      sha256 "0800aff1056ff12acd086021f53f688e97cbd2e734f1ac1fff857a47892a26ee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_linux_amd64.tar.gz"
      sha256 "d05bf59822f239db8da175a743613f43cd5a17ef066ed18d77218100fb76207e"
    end
    on_arm do
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_linux_arm64.tar.gz"
      sha256 "32710b3f1dcc91ad297d5edfa9b25e791158a561357affa3671c7af65a67b26b"
    end
  end

  # No zap stanza required
end
