# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpx" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "eaaa0ac14d95505e0a466eb260154311d8f38a34a136dcd6845bc40e493908f1"
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8152de0133dc0205d544e10a965b2cd453982fd2124fb7f6847623dd2ed65826"
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5a0ad297e9bd1a9c131fa43626ac8109573fb2f1cef331278ca99326019ea9ce"
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d457936a86759baa70b73babc75eff27d0072d311678c0d54f9e74834d76a2cc"
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpx"
  desc "Unix-native CLI wrapper for MCP servers"
  homepage "https://github.com/lydakis/mcpx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpx"

  # No zap stanza required
end
