# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpx" do
  name "mcpx"
  desc "Unix-native CLI wrapper for MCP servers"
  homepage "https://github.com/lydakis/mcpx"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpx"

  on_macos do
    on_intel do
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_darwin_amd64.tar.gz"
      sha256 "e10b7f0656acd936131b512b28c650c0f6cc899fe61c9e46ea2aec4b7d6996ab"
    end
    on_arm do
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_darwin_arm64.tar.gz"
      sha256 "3d9da12d1c93d01ce167129d8187ca8a7e32af0aa49720508b30efb27ed15ab9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_linux_amd64.tar.gz"
      sha256 "ee47458befe77392334f0c957d2f96d7c8760e2997012afe8d2d495fb30d8f31"
    end
    on_arm do
      url "https://github.com/lydakis/mcpx/releases/download/v#{version}/mcpx_#{version}_linux_arm64.tar.gz"
      sha256 "880b5778572964f4aad97a1fb052d4e34e3c8eaf6c5a529671ec0f31e85d65c0"
    end
  end

  # No zap stanza required
end
